name: Build Signed Release APK

on:
  release:
    types: [published]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-signed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release-keystore.jks
        
    - name: Build signed release APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_FILE: release-keystore.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: Upload signed release APK
      uses: actions/upload-artifact@v4
      with:
        name: signed-release-apk
        path: |
          **/build/outputs/apk/release/*.apk
        retention-days: 90