name: Build Signed Release APK

on:
  release:
    types: [published]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-signed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > ${{ github.workspace }}/release-keystore.jks
        ls -la ${{ github.workspace }}/release-keystore.jks
        echo "Keystore file created at: ${{ github.workspace }}/release-keystore.jks"
        
    - name: Debug environment variables
      run: |
        echo "KEYSTORE_FILE: $KEYSTORE_FILE"
        echo "KEYSTORE_PASSWORD is set: $([[ -n "$KEYSTORE_PASSWORD" ]] && echo "yes" || echo "no")"
        echo "KEY_ALIAS: $KEY_ALIAS"
        echo "KEY_PASSWORD is set: $([[ -n "$KEY_PASSWORD" ]] && echo "yes" || echo "no")"
        echo "Working directory: $(pwd)"
        echo "Keystore exists: $(test -f "$KEYSTORE_FILE" && echo "yes" || echo "no")"
      env:
        KEYSTORE_FILE: ${{ github.workspace }}/release-keystore.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: Build signed release APK
      run: ./gradlew assembleRelease --info
      env:
        KEYSTORE_FILE: ${{ github.workspace }}/release-keystore.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: Upload signed release APK
      uses: actions/upload-artifact@v4
      with:
        name: signed-release-apk
        path: |
          **/build/outputs/apk/release/*.apk
        retention-days: 90